// ============================================================================
// ZIPGEN - In-memory Vite project zip generation via archiver
// ============================================================================

import archiver from 'archiver';
import { PassThrough } from 'stream';
import type { WidgetAnalysis } from './types.js';
import { generateTsx } from './codegen.js';

function packageJson(projectName: string): string {
  return JSON.stringify(
    {
      name: projectName,
      version: '0.1.0',
      scripts: { dev: 'vite', build: 'tsc && vite build' },
      dependencies: {
        '@dashcraft/core': '^0.1.0',
        react: '^19.0.0',
        'react-dom': '^19.0.0',
      },
      devDependencies: {
        '@vitejs/plugin-react': '^4.3.4',
        typescript: '^5.7.0',
        vite: '^6.0.0',
      },
    },
    null,
    2
  );
}

const viteConfig = `import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'

export default defineConfig({
  plugins: [react()],
})
`;

const tsConfig = JSON.stringify(
  {
    compilerOptions: {
      target: 'ES2020',
      lib: ['ES2020', 'DOM', 'DOM.Iterable'],
      module: 'ESNext',
      skipLibCheck: true,
      moduleResolution: 'Bundler',
      allowImportingTsExtensions: true,
      resolveJsonModule: true,
      isolatedModules: true,
      noEmit: true,
      jsx: 'react-jsx',
      strict: true,
    },
    include: ['src'],
  },
  null,
  2
);

const indexHtml = (projectName: string) => `<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>${projectName}</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.tsx"></script>
  </body>
</html>
`;

const mainTsx = `import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
import './index.css'
import App from './App.tsx'

createRoot(document.getElementById('root')!).render(
  <StrictMode>
    <App />
  </StrictMode>,
)
`;

const appTsx = `import { GeneratedDashboard } from './Dashboard.tsx'

export default function App() {
  return <GeneratedDashboard />
}
`;

const indexCss = `*, *::before, *::after {
  box-sizing: border-box;
}

body {
  margin: 0;
  font-family: system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
  background: #f8fafc;
}
`;

const readme = (projectName: string) => `# ${projectName}

Generated by [@dashcraft/mcp-codegen](https://github.com/nishant-chaudhary/dashcraft).

## Getting started

\`\`\`bash
npm install
npm run dev
\`\`\`

The dashboard component is in \`src/Dashboard.tsx\`.
Customise widget data by replacing the placeholder \`value={0}\` / \`data={[]}\` props.
`;

export async function generateProjectZip(
  widgets: WidgetAnalysis[],
  projectName: string = 'my-dashboard'
): Promise<string> {
  const dashboardTsx = generateTsx(widgets, 'GeneratedDashboard');

  return new Promise<string>((resolve, reject) => {
    const chunks: Buffer[] = [];
    const passthrough = new PassThrough();

    passthrough.on('data', (chunk: Buffer) => chunks.push(chunk));
    passthrough.on('end', () => {
      const buffer = Buffer.concat(chunks);
      resolve(buffer.toString('base64'));
    });
    passthrough.on('error', reject);

    const archive = archiver('zip', { zlib: { level: 9 } });
    archive.on('error', reject);
    archive.pipe(passthrough);

    const root = `${projectName}/`;

    archive.append(packageJson(projectName), { name: `${root}package.json` });
    archive.append(viteConfig, { name: `${root}vite.config.ts` });
    archive.append(tsConfig, { name: `${root}tsconfig.json` });
    archive.append(indexHtml(projectName), { name: `${root}index.html` });
    archive.append(readme(projectName), { name: `${root}README.md` });
    archive.append(mainTsx, { name: `${root}src/main.tsx` });
    archive.append(appTsx, { name: `${root}src/App.tsx` });
    archive.append(dashboardTsx, { name: `${root}src/Dashboard.tsx` });
    archive.append(indexCss, { name: `${root}src/index.css` });

    archive.finalize();
  });
}
